//
//  LevelData.swift
//  RMA-app
//
//  Created by student on 09.02.2024..
//

import Foundation
import Combine

class LevelData: ObservableObject {
    //static let shared = LevelData()
    
    @Published var levels: [Level] = [
        Level(gameName: "The Legend of Zelda: Breath of the Wild", name: "Oman Au Shrine (Great Plateau)", content: "To reach this shrine, you need to complete the Magnesis Trial. Use the Magnesis Rune on metal blocks to manipulate them and create paths. Navigate through the shrine by moving metal blocks, avoiding hazards, and solving puzzles. Use Magnesis to find hidden chests containing valuable loot."),
        Level(gameName: "The Legend of Zelda: Breath of the Wild", name: "Ja Baij Shrine (Great Plateau)", content: "This shrine's trial is called “Bomb Trial“. Use the Remote Bombs Rune to blast through obstacles and solve puzzles. Detonate bombs to clear paths, activate switches, and defeat enemies. Pay attention to your surroundings for hints on how to progress."),
        Level(gameName: "The Legend of Zelda: Breath of the Wild", name: "Keh Namut Shrine (Necluda Sea)", content: "Complete the “Halt the Tilt“ trial in this shrine. Use the Stasis Rune to freeze moving platforms and objects. Time your movements carefully to navigate through the shrine's moving parts. Use Stasis to freeze objects in mid-air and create platforms for traversal."),
        Level(gameName: "The Legend of Zelda: Breath of the Wild", name: "Kaam Ya'tak Shrine (Hyrule Field)", content: "This shrine's trial is “Trial of Power.“ Utilize your combat skills to defeat enemies and solve puzzles. Clear rooms of enemies to progress further into the shrine. Use the environment to your advantage, such as explosive barrels and elevated platforms."),
        Level(gameName: "The Legend of Zelda: Breath of the Wild", name: "Shee Vaneer Shrine (Eldin Mountains)", content: "Complete the “Tandem“ trial inside this shrine. Utilize both the Cryonis and Magnesis Runes to solve puzzles. Freeze columns of water with Cryonis to create platforms. Use Magnesis to move metal blocks and create paths through the shrine."),
        Level(gameName: "Little Nightmares", name: "The Prison", content: "Begin by waking up as Six, the protagonist, in a dark and eerie room. Move to the right and climb up the crates to reach the top. Navigate through the prison, avoiding detection by the grotesque creatures. Use stealth and timing to progress through the level without getting caught."),
        Level(gameName: "Little Nightmares", name: "The Lair", content: "After escaping the prison, continue through the ship until you reach the lair. Sneak past the Twin Chefs by hiding in the kitchen furniture and avoiding their line of sight. Use the environment to your advantage, including hiding under tables and behind objects. Time your movements carefully to avoid making noise and alerting the chefs."),
        Level(gameName: "Little Nightmares", name: "The Lair - Kitchen", content: "In this section, you'll navigate the treacherous kitchen filled with dangers. Avoid traps such as falling meat hooks and swinging cages by timing your movements. Use objects in the environment to distract enemies and create openings for escape. Stay alert and be prepared to react quickly to unforeseen hazards."),
        Level(gameName: "Little Nightmares", name: "The Lair - Guest Area", content: "After escaping the kitchen, you'll find yourself in the guest area of the ship. Explore the environment to find a way past the guests without being caught. Use stealth to hide from the guests and avoid their gaze as you progress through the area. Look for openings and opportunities to sneak past unnoticed."),
        Level(gameName: "Little Nightmares", name: "The Lair - Guest Quarters", content: "Navigate through the dark and eerie guest quarters, filled with unsettling sights. Solve puzzles and overcome obstacles to progress further into the ship. Pay attention to your surroundings for clues on how to proceed. Stay vigilant and be prepared for unexpected encounters with the ship's inhabitants."),
        Level(gameName: "Heavy Rain", name: "Prologue", content: "Follow Jason through the crowded mall. Press the correct buttons when prompted to interact with Jason and keep him in sight. Pay attention to the Quick Time Events (QTEs) to ensure Jason's safety."),
        Level(gameName: "Heavy Rain", name: "The Mall", content: "Navigate through the panicked crowd to search for Jason. Follow the on-screen prompts to interact with NPCs and search for clues. Use the directional buttons or left stick to move Ethan through the mall. Look for Jason's distinctive red balloon to help locate him."),
        Level(gameName: "Heavy Rain", name: "Father ans Son", content: "Interact with Shaun and try to comfort him. Follow the on-screen prompts to choose responses and actions during the conversation. Pay attention to Shaun's emotional state and try to reassure him."),
        Level(gameName: "Heavy Rain", name: "The Park", content: "As Scott Shelby, approach Lauren Winter in the park. Use the dialogue options to ask her questions about her son's death. Listen to her responses and follow up with appropriate questions. Pay attention to the conversation and gather as much information as possible."),
        Level(gameName: "Heavy Rain", name: "Paparazzi", content: "Investigate the crime scene as Norman Jayden. Use the ARI to analyze evidence and reconstruct the scene. Follow the prompts to interact with objects and gather clues. Pay attention to the environment and use the ARI's features to your advantage."),
        Level(gameName: "Red Dead Redemption II", name: "Outlaws from the West", content: "This mission serves as an introduction to the game mechanics. Follow the on-screen prompts to learn basic controls like movement, shooting, and horse riding. Listen to the instructions provided by your gang members and participate in the robbery."),
        Level(gameName: "Red Dead Redemption II", name: "Enter, Pursued by a Memory", content: "In this mission, you'll learn how to hunt. Follow your companion, Javier, as he tracks the bear. Use your bow to shoot the bear when prompted. Aim for its head or heart for a clean kill. After the bear attack, help carry it back to camp."),
        Level(gameName: "Red Dead Redemption II", name: "Old Friends", content: "This mission introduces you to the camp mechanics and introduces you to more characters. Follow Dutch and the gang as you move from Colter to Horseshoe Overlook. Along the way, you'll get familiar with the camp setup, including contributing money and resources to the camp's provisions."),
        Level(gameName: "Red Dead Redemption II", name: "Who the Hell is Leviticus Cornwall?", content: "In this mission, you'll participate in a train robbery. Follow Dutch's plan to stop the train and steal the supplies. Be prepared for a shootout with the lawmen onboard. Use cover effectively, aim carefully, and prioritize targets to ensure a successful robbery."),
        Level(gameName: "Red Dead Redemption II", name: "Eastward Bound", content: "This mission involves moving the camp to a new location. Help pack up the camp and then ride out with Dutch, Charles, and Javier to scout ahead. Along the way, you'll encounter some trouble which you'll need to handle. Follow Dutch's lead and deal with the situation to complete the mission."),
        Level(gameName: "Diablo IV", name: "The Return to Sanctuary", content: "Begin by selecting your character class: Barbarian, Sorceress, or Druid. Follow the introductory cutscene and dialogue to learn about the current state of Sanctuary. Explore the starting area to familiarize yourself with movement and combat controls. Complete any initial tasks or tutorials provided by NPCs to gain experience and equipment."),
        Level(gameName: "Diablo IV", name: "The Lost Caravan", content: "Receive a quest to investigate a missing caravan in a nearby area. Journey through the wilderness, battling monsters and exploring dungeons along the way. Use your character's abilities and skills to defeat enemies and overcome obstacles. Locate the missing caravan and rescue any survivors or retrieve any valuable items."),
        Level(gameName: "Diablo IV", name: "The Cursed Village", content: "Receive reports of a village plagued by demonic forces. Travel to the cursed village and speak with the townsfolk to learn about their plight. Investigate the source of the curse by exploring nearby dungeons or caves. Battle through hordes of demons and confront the source of the curse to lift it from the village."),
        Level(gameName: "Diablo IV", name: "The Witch's Lair", content: "Encounter rumors of a powerful witch terrorizing the countryside. Track down the witch's lair by following clues and speaking with NPCs. Navigate through the witch's lair, facing traps, puzzles, and powerful minions. Confront the witch in a climactic battle to put an end to her dark schemes."),
        Level(gameName: "Diablo IV", name: "The Ruined Keep", content: "Receive reports of an ancient keep overrun by demonic forces. Journey to the ruined keep and battle your way through its corridors and chambers. Discover the keep's dark history and the source of its corruption. Confront the demon lord or powerful entity controlling the keep and vanquish it to restore peace to the land."),
        Level(gameName: "The Last of Us: Part I", name: "Prologue: Hometown", content: "Control Joel in his house. Follow Sarah's instructions and interact with her and other objects in the house. After controlling Sarah, follow her instructions to find Joel. Once chaos erupts, follow Sarah as she navigates through the house. Complete QTE prompts to escape the infected and military."),
        Level(gameName: "The Last of Us: Part I", name: "The Quarantine Zone", content: "Follow Tess through the streets of Boston. Navigate through alleys and buildings while avoiding or engaging with hostile survivors and military patrols. Reach Robert's warehouse and confront him to retrieve stolen goods. Defeat Robert's guards and retrieve the stolen weapons."),
        Level(gameName: "The Last of Us: Part I", name: "The Outskirts: Downtown", content: "Follow Tess and Joel as they navigate through the streets of the quarantine zone. Encounter infected enemies for the first time. Use stealth to avoid them or engage in combat if necessary. Solve environmental puzzles to progress, such as finding a way over a barricade or through a locked door. Reach the Capitol building and confront the soldiers guarding it."),
        Level(gameName: "The Last of Us: Part I", name: "Bill's Town: The Woods", content: "Meet Bill in his fortified town and follow him to his safe house. Search the town for a car battery and bring it back to Bill. Solve environmental puzzles to progress, such as finding a ladder or opening a locked gate. Encounter various infected and hostile survivors. Use stealth and combat to navigate through the town safely."),
        Level(gameName: "The Last of Us: Part I", name: "Pittsburgh: Alone and Forsaken", content: "Control Joel as he and Ellie navigate through the abandoned streets of Pittsburgh. Encounter hostile human factions. Use stealth and combat to overcome them. Solve environmental puzzles to progress, such as finding a way over a collapsed bridge or through a locked gate. Work together with Ellie to overcome obstacles and find a way out of Pittsburgh."),
       ]
}
